### ISSUE TITLE
Address Ember CLI Deploy/gzip issues

### ISSUE THREAD

**Issue by addyosmani** [addyosmani/ember-progressive-webapp#3]
> I looked at your error, and basically the workaround is to disable gzip on json files like you suggested in the Gist comment. You can see how we do it on the API doc site here.
> 
> That being said, we should probably make a pull request to the ember-cli-deploy ecosystem to sort of leave fastboot files alone. Most of these files will end up in the fastboot folder inside whatever the build directory is (in the case of Ember CLI deploy, tmp/deploy-dist/fastboot).

**Comment by achambers** [comment]
Hi @addyosmani. It's a shame that this issue has only appeared on my radar now. I know it was 3.5 months ago but is there anything we can do to make things clearer for you? Are there any questions you still have in terms of this?

If we can help out with clarifying anything with the above, please just holler and one of the ember-cli-deploy team will be happy to help out.

/cc @lukemelia @ghedamat
